Skip autostart if prlctl is missing #PSBM-139428
Signed-off-by: Pavel Vokhmyanin <pvokhmyanin@virtuozzo.com>

diff --git a/etc/systemd.d/vz b/etc/systemd.d/vz
--- a/etc/systemd.d/vz
+++ b/etc/systemd.d/vz
@@ -239,6 +239,11 @@ start_env()
 {
 	local pid pids iter
 
+	if ! which prlctl >/dev/null 2>&1; then
+		echo "prlctl is missing, skip autostart"
+		return
+	fi
+
 	target=`readlink /etc/systemd/system/default.target`
 	if [ -n "$target" ]; then
 		target=`basename $target`
