Load vz-related modules on service start #PSBM-139428
In VHI scenario vzctl is missing from the server initially, and only
installed when CT role is configured for the host. This leads to vz
modules being absent on service startup until the next reboot. Lets
check if modules are missing, and load them if necessary.

Signed-off-by: Pavel Vokhmyanin <pvokhmyanin@virtuozzo.com>

diff --git a/etc/systemd.d/vz b/etc/systemd.d/vz
--- a/etc/systemd.d/vz
+++ b/etc/systemd.d/vz
@@ -11,6 +11,9 @@ NETCLASSES=/etc/vz/conf/networks_classes
 SYSFS_PERM=/sys/fs/cgroup/ve/ve.default_sysfs_permissions
 SUSPEND_CONF_DIR=/etc/vz/vzreboot
 
+VZ_MODULES=/etc/modules-load.d/vz.conf
+PLOOP_MODULES=/etc/modules-load.d/ploop.conf
+
 get_parallel()
 {
 	[ -n "${VE_PARALLEL}" -a "${VE_PARALLEL}" != "0" ] && return
@@ -279,6 +282,29 @@ start_env()
 	return 0
 }
 
+load_module_list()
+{
+	module=$1
+	if [ ! -f "$module" ]; then
+		echo "Cannot find module-load config $module"
+		return 1
+	fi
+
+	toload=`grep -v "^\s*#" "$module" | grep .`
+	for mname in $toload; do
+		if [ ! -d "/sys/module/$mname" ]; then
+			modprobe $mname && echo "Module $mname loaded" || echo "Unable to load $mname"
+		fi
+	done
+}
+
+load_modules()
+{
+	for module_name in "$VZ_MODULES" "$PLOOP_MODULES"; do
+		load_module_list "$module_name"
+	done
+}
+
 start()
 {
 	if ! grep -q '^[[:space:]]*SERVER_UUID=' $VZCONF; then
@@ -287,6 +313,7 @@ start()
 		[ -n "$uuid" ] && echo -e "\nSERVER_UUID=$uuid" >> $VZCONF
 	fi
 
+	load_modules
 	setup_ve_sysfs
 	setup_net
 	setup_tc
